// Mocks generated by Mockito 5.4.6 from annotations
// in plc/test/features/preaching_themes/data/repositories/preaching_theme_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:plc/core/storage/local_storage_service.dart' as _i2;
import 'package:plc/features/preaching_themes/data/datasources/local/preaching_theme_local_data_source.dart'
    as _i5;
import 'package:plc/features/preaching_themes/data/datasources/remote/preaching_theme_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalStorageService_0 extends _i1.SmartFake
    implements _i2.LocalStorageService {
  _FakeLocalStorageService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PreachingThemeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreachingThemeRemoteDataSource extends _i1.Mock
    implements _i3.PreachingThemeRemoteDataSource {
  MockPreachingThemeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<String>> getPreachingThemes() => (super.noSuchMethod(
        Invocation.method(
          #getPreachingThemes,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}

/// A class which mocks [PreachingThemeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreachingThemeLocalDataSource extends _i1.Mock
    implements _i5.PreachingThemeLocalDataSource {
  MockPreachingThemeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalStorageService get storageService => (super.noSuchMethod(
        Invocation.getter(#storageService),
        returnValue: _FakeLocalStorageService_0(
          this,
          Invocation.getter(#storageService),
        ),
      ) as _i2.LocalStorageService);

  @override
  _i4.Future<List<String>> getAllPreachingThemes() => (super.noSuchMethod(
        Invocation.method(
          #getAllPreachingThemes,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> savePreachingThemes(List<String>? themes) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreachingThemes,
          [themes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getLastSyncDate() => (super.noSuchMethod(
        Invocation.method(
          #getLastSyncDate,
          [],
        ),
        returnValue: _i4.Future<DateTime?>.value(),
      ) as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> setLastSyncDate(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #setLastSyncDate,
          [date],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
