// Mocks generated by Mockito 5.4.5 from annotations
// in plc/test/features/preachers/presentation/pages/preacher_profile_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:plc/features/preachers/domain/usecases/get_preacher_by_id.dart'
    as _i2;
import 'package:plc/features/preachers/presentation/bloc/preacher_profile_bloc.dart'
    as _i4;
import 'package:plc/features/preachers/presentation/bloc/preacher_profile_event.dart'
    as _i6;
import 'package:plc/features/preachers/presentation/bloc/preacher_profile_state.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetPreacherById_0 extends _i1.SmartFake
    implements _i2.GetPreacherById {
  _FakeGetPreacherById_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreacherProfileState_1 extends _i1.SmartFake
    implements _i3.PreacherProfileState {
  _FakePreacherProfileState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PreacherProfileBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreacherProfileBloc extends _i1.Mock
    implements _i4.PreacherProfileBloc {
  MockPreacherProfileBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPreacherById get getPreacherById => (super.noSuchMethod(
        Invocation.getter(#getPreacherById),
        returnValue: _FakeGetPreacherById_0(
          this,
          Invocation.getter(#getPreacherById),
        ),
      ) as _i2.GetPreacherById);

  @override
  _i3.PreacherProfileState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakePreacherProfileState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.PreacherProfileState);

  @override
  _i5.Stream<_i3.PreacherProfileState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.PreacherProfileState>.empty(),
      ) as _i5.Stream<_i3.PreacherProfileState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i6.PreacherProfileEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.PreacherProfileEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.PreacherProfileState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.PreacherProfileEvent>(
    _i7.EventHandler<E, _i3.PreacherProfileState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i6.PreacherProfileEvent, _i3.PreacherProfileState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onChange(_i7.Change<_i3.PreacherProfileState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
